version: '3.8'
services:
  validator:
    build:
      context: .
      dockerfile: subnet/validator/Dockerfile
    container_name: alphamind-validator
    ports:
      - "8003:8000"
    environment:
      - AM_OUT_DIR=/data/out
      - AM_API_TOKEN=${AM_API_TOKEN:-dev}
      - AM_CORS_ORIGINS=${AM_CORS_ORIGINS:-http://localhost:8003}
      - AM_RATE_LIMIT_PER_MIN=${AM_RATE_LIMIT_PER_MIN:-60}
      - AM_REQUIRE_HOTKEY=${AM_REQUIRE_HOTKEY:-1}
      - AM_REQUIRE_SIGNING=${AM_REQUIRE_SIGNING:-1}
      - AM_REQUIRE_PUBLISH=${AM_REQUIRE_PUBLISH:-1}
      - AM_PUBLISH_MODE=${AM_PUBLISH_MODE:-auto}
      - AM_REJECT_HMAC=${AM_REJECT_HMAC:-1}
      - AM_REQUIRE_RESERVES=${AM_REQUIRE_RESERVES:-1}
      - AM_PRICE_QUORUM=${AM_PRICE_QUORUM:-0.7}
      - AM_PRICE_STALE_SEC=${AM_PRICE_STALE_SEC:-120}
      - AM_ADMIN_TOKEN=${AM_ADMIN_TOKEN:-admin}
    volumes:
      - ./subnet/out:/data/out
      - ./subnet/out/state:/data/out/state
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/readyz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s


