# TAO20 Enhanced Miner Configuration
# Configuration for TAO20 Arbitrage Miner (Authorized Participant)

# Bittensor Network Configuration
bittensor:
  network: "finney"  # or "test" for testnet
  netuid: 20
  wallet:
    name: "miner_wallet"
    hotkey: "miner_hotkey"
    path: "~/.bittensor/wallets"

# Contract and Network Configuration
contracts:
  tao20_address: "0x1234567890123456789012345678901234567890"
  vault_address: "0x2345678901234567890123456789012345678901"
  nav_oracle_address: "0x3456789012345678901234567890123456789012"
  web3_provider: "https://mainnet.bevm.io"
  
# EVM Configuration
evm:
  private_key: "${TAO20_MINER_PRIVATE_KEY}"  # Environment variable
  gas_price_multiplier: 1.2
  max_gas_limit: 500000

# Arbitrage Configuration
arbitrage:
  min_spread_threshold: 0.005  # 0.5% minimum spread for arbitrage
  max_transaction_size: 10000000000000000000  # 10 TAO in wei
  min_transaction_size: 100000000000000000   # 0.1 TAO in wei
  volume_target_per_hour: 100000000000000000000  # 100 TAO per hour
  
# Portfolio Management
portfolio:
  max_inventory_ratio: 0.5    # Max 50% of portfolio in TAO20
  rebalance_threshold: 0.8    # Rebalance when 80% of max ratio reached
  risk_management:
    max_daily_loss: 0.05      # 5% max daily loss
    stop_loss_threshold: 0.1  # 10% stop loss
    
# Performance Optimization
performance:
  transaction_interval_base: 120  # 2 minutes base interval
  transaction_interval_variance: 30  # ±30 seconds variance
  batch_size_optimization: true
  gas_optimization: true
  
# Monitoring and Alerts
monitoring:
  nav_update_interval: 30     # 30 seconds
  price_staleness_threshold: 300  # 5 minutes
  arbitrage_alert_threshold: 0.01  # 1%
  performance_report_interval: 600  # 10 minutes
  
# Logging Configuration
logging:
  level: "INFO"
  file: "logs/miner.log"
  max_file_size: "50MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# API Configuration (for external monitoring)
api:
  enabled: true
  port: 8080
  host: "0.0.0.0"
  endpoints:
    - "/status"
    - "/performance"
    - "/arbitrage"
