version: '3.8'
services:
  validator:
    image: ${VALIDATOR_IMAGE:-alphamind/validator:latest}
    container_name: alphamind-validator
    restart: unless-stopped
    environment:
      - AM_OUT_DIR=/data/out
      - AM_API_TOKEN=${AM_API_TOKEN}
      - AM_ADMIN_TOKEN=${AM_ADMIN_TOKEN}
      - AM_CORS_ORIGINS=${AM_CORS_ORIGINS}
      - AM_REQUIRE_SIGNING=${AM_REQUIRE_SIGNING:-1}
      - AM_REQUIRE_HOTKEY=${AM_REQUIRE_HOTKEY:-1}
      - AM_REJECT_HMAC=${AM_REJECT_HMAC:-1}
      - AM_REQUIRE_PUBLISH=${AM_REQUIRE_PUBLISH:-1}
      - AM_REQUIRE_RESERVES=${AM_REQUIRE_RESERVES:-1}
      - AM_PRICE_QUORUM=${AM_PRICE_QUORUM:-0.7}
      - AM_PRICE_STALE_SEC=${AM_PRICE_STALE_SEC:-120}
      - AM_CHAIN=${AM_CHAIN:-0}
      - AM_RPC_URL=${AM_RPC_URL}
      - AM_CHAIN_PRIVKEY=${AM_CHAIN_PRIVKEY}
      - AM_REGISTRY_ADDR=${AM_REGISTRY_ADDR}
      - AM_VALIDATORSET_ADDR=${AM_VALIDATORSET_ADDR}
    ports:
      - "8000:8000"
    volumes:
      - ${AM_OUT_HOST_DIR:-./out}:/data/out

